class_template_app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.IndexPage.as_view(), name="index"),
    path("list/", views.SchoolListView.as_view(), name="list"),
    path("create/", views.SchoolCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", views.SchoolDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", views.SchoolUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.SchoolDeleteView.as_view(), name="delete")
]

class_template_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("class_template_app.urls"))
]

class_template_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=264)
    principal = models.CharField(max_length=264)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=264)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(
        School, related_name="students", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

class_template_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from . import models

# Create your views here.


class IndexPage(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = "schools"
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = "school"
    model = models.School
    template_name = 'class_template_app/school_details.html'


class SchoolCreateView(CreateView):
    fields = "__all__"
    model = models.School
    template_name = 'class_template_app/school_create.html'


class SchoolUpdateView(UpdateView):
    fields = "__all__"
    model = models.School
    template_name = 'class_template_app/school_create.html'


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("app:list")

class_template_app/templates/class_template_app/school_confirm_delete.html
<!DOCTYPE html>

    {% extends 'base.html' %}

        {% block dynamic_block %}
        <h2>Delete {{school.name}}</h2>
        <form method="POST">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Delete" />
            <a href="{% url 'app:detail' pk=school.id %}">Cancel</a>
        </form>
            
        {% endblock %}

class_template_app/templates/class_template_app/school_create.html
<!DOCTYPE html>
    {% extends 'base.html' %}
        {% if not form.instance.pk %}
            <h1>Create School</h1>
        {% else %}
            <h1>Update School</h1>
        {% endif %}


        {% block dynamic_block %}
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" name="Submit" />
            </form>
        {% endblock %}

class_template_app/templates/class_template_app/school_details.html
<!DOCTYPE html>
    {% extends 'base.html' %}

        {% block dynamic_block %}
            <div>
                <div>School Name : {{school.name}}</div>
                <div>Principal Name : {{school.principal}}</div>
                <div>Students : 
                    <ol>
                        {% for student in school.students.all %}
                            <li>{{student.name}}</li>
                        {% endfor %}
                    </ol>
                </div>
                <a class="btn btn-warning" href="{% url 'app:update' pk=school.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'app:delete' pk=school.id %}">Delete</a>
            </div>
        {% endblock %}

class_template_app/templates/class_template_app/school_list.html
<!DOCTYPE html>
{% extends 'base.html' %}

    {% block dynamic_block %}

        <ol>
            {% for school in schools %}
                <h2>
                    <li><a href="{% url 'app:detail' pk=school.id %}">{{school}}</a></li>
                </h2>
            {% endfor %}
        </ol>
    
    {% endblock %}

class_template_app/templates/class_template_app/template_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Template Demo</title>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'app:index' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:list' %}">School List</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:create' %}">Create School</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block dynamic_block %}
      {% endblock %}
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

    {% block dynamic_block %}
        <h1>I am index</h1>
    {% endblock %}